<a href="https://colab.research.google.com/github/saqibansari07121996/CV/blob/main/SalaryIncrement.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
inputs = np.array([[18,2], [20,3], [21, 4],  
                   [35,15], [36,16], [38, 18]])

In [ ]:
inputs=inputs/inputs.mean()
inputs

array([[0.95575221, 0.10619469],
       [1.0619469 , 0.15929204],
       [1.11504425, 0.21238938],
       [1.85840708, 0.79646018],
       [1.91150442, 0.84955752],
       [2.01769912, 0.95575221]])

In [ ]:
inputs.shape

(6, 2)

In [ ]:
outputs = np.array([0, 0, 0, 1, 1, 1])

In [ ]:
outputs.shape

(6,)

In [ ]:
weights=np.array([0.0,0.0])

In [ ]:
learning_rate=0.1

In [ ]:
def step_func(sum):
  if sum>=1:
    return 1
  return 0

In [ ]:
def calc_out(instance):
  s=instance.dot(weights)
  return step_func(s)

In [ ]:
calc_out(inputs[4])

0

In [ ]:
def train():
  total_error=1
  while(total_error!=0):
    total_error=0
    for i in range(len(outputs)):
      predict=calc_out(inputs[i])
      error=abs(outputs[i]-predict)
      total_error+=error
      if error>0:
        for j in range(len(weights)):
          weights[j]=weights[j]+(learning_rate*inputs[i][j]*error)
          print('Updated weights: ' + str(weights[j]))
    print("Total Error: "+ str(total_error))
                         

In [ ]:
train()

Updated weights: 0.1858407079646018
Updated weights: 0.07964601769911506
Updated weights: 0.37699115044247794
Updated weights: 0.16460176991150444
Updated weights: 0.5787610619469028
Updated weights: 0.2601769911504425
Total Error: 3
Total Error: 0


In [ ]:
weights

array([0.57876106, 0.26017699])

In [ ]:
calc_out(np.array([17,5]))

1

In [ ]:
calc_out(np.array([47,10]))

1

In [ ]:
calc_out(np.array([25,8]))

1

In [ ]:
calc_out(np.array([31,20]))

1

In [ ]:
calc_out(np.array([21,4]))

1

In [ ]:
calc_out(np.array([18,2]))

1

In [ ]:
net_sum=inputs.dot(weights)
net_sum

array([0.58078158, 0.65605764, 0.70060302, 1.28279427, 1.32733965,
       1.41643042])

In [ ]:
step_func(net_sum[0])

0

In [ ]:
calc_out(inputs[0])

0

In [ ]:
test_inputs = np.array([[17,5], [25,8],  
                        [45,10], [31,20]])

In [ ]:
test_inputs=test_inputs/test_inputs.mean()
test_inputs

array([[0.8447205 , 0.2484472 ],
       [1.24223602, 0.39751553],
       [2.23602484, 0.49689441],
       [1.54037267, 0.99378882]])

In [ ]:
calc_out(test_inputs[0])

1

In [ ]:
calc_out(test_inputs[2])

1

In [ ]:
calc_out(test_inputs[1])

0

In [ ]:
calc_out(test_inputs[3])

1

In [ ]:
calc_out(test_inputs[0])

0

In [ ]:
age=float(input("Enter your Age in Years\n"))
exp=float(input('Enter your Experience in Years\n'))
age=age/30
exp=exp/12

Enter your Age in Years
22
Enter your Experience in Years
1


In [ ]:
if calc_out(np.array([age,exp]))==1:
  print("You will get an Increment!")
else:
  print("Sorry, you gotta do some work!")


Sorry, you gotta do some work!
